### PR TITLE
Remove computation graph

### PR DESCRIPTION
**Pull request by PavelMakarchuk**

### CODE REVIEW

**Comment by PavelMakarchuk** [comment]
@MaxGhenis ready for review

**Review by MaxGhenis — CHANGES_REQUESTED** [review]
remove the graph creation part too and unnecessary imports and requirements.txt entries

**Comment by MaxGhenis** [comment]
this says `fix API issue` but i don't see anything about that in the PR

**Comment by PavelMakarchuk** [comment]
> this says `fix API issue` but i don't see anything about that in the PR

adjusted - it was a local change

**Review by MaxGhenis — APPROVED** [review]

**Pull request merged**
